spring:
  datasource:
    url: jdbc:mysql://ec2-15-165-2-129.ap-northeast-2.compute.amazonaws.com:3306/testDB?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: test
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  redis:
    host: ec2-15-165-2-129.ap-northeast-2.compute.amazonaws.com
    port: 6379
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465
AdminMail:
  id: mainproject3355@gmail.com
  password: ${EMAIL_PASSWORD}