insert into interest(interest_id, name)
values(1,'교육'),
    (2,'미디어'),
    (3,'제조'),
    (4,'금융'),
    (5,'에너지/친환경'),
    (6,'유통/물류'),
    (7,'의료/헬스 케어'),
    (8,'건설'),
    (9,'기타');
insert into skill(skill_id, name, Skill_Sort)
values(1,'Java', 'BACKEND'),
    (2,'JavaScript', 'FRONTEND'),
    (3,'TypeScript', 'FRONTEND'),
    (4,'React', 'FRONTEND'),
    (5,'Vue', 'FRONTEND'),
    (6,'Svelte', 'FRONTEND'),
    (7,'Nextjs', 'FRONTEND'),
    (8,'Nodejs', 'BACKEND'),
    (9,'Spring', 'BACKEND'),
    (10,'Go', 'BACKEND'),
    (11,'Nestjs', 'BACKEND'),
    (12,'Kotlin', 'BACKEND'),
    (13,'Express', 'BACKEND'),
    (14,'MySQL', 'BACKEND'),
    (15,'MongoDB', 'BACKEND'),
    (16,'Python', 'BACKEND'),
    (17,'Django', 'BACKEND'),
    (18,'php', 'BACKEND'),
    (19,'GraphQL', 'BACKEND'),
    (20,'Firebase', 'BACKEND'),
    (21,'Flutter', 'ETC'),
    (22,'Swift', 'ETC'),
    (23,'ReactNative', 'ETC'),
    (24,'Unity', 'ETC'),
    (25,'AWS', 'ETC'),
    (26,'Kubernetes', 'ETC'),
    (27,'Docker', 'ETC'),
    (28,'Git', 'ETC'),
    (29,'Figma', 'ETC'),
    (30,'Zeplin', 'ETC'),
    (31,'Jest', 'ETC');


